# Generated by Django 6.0.5 on 2026-06-08 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_userprofile_employee'),
        ('site_settings', '0006_remove_expected_exit_setting'),
    ]

    operations = [
    ]
