# Generated by Django 6.0.5 on 2026-05-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='vehicle_expected_exit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
