# Generated by Django 6.0.5 on 2026-05-22 07:57

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0002_jobcard_vehicle_expected_exit_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='gst_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5),
        ),
        migrations.CreateModel(
            name='JobCardPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card'), ('netbanking', 'Net Banking'), ('cheque', 'Cheque'), ('other', 'Other')], default='cash', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='jobcards.jobcard')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
