# Generated by Django 6.0.5 on 2026-05-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0009_alter_jobcardproduct_service_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='job_card_number',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
