# Generated by Django 6.0.5 on 2026-06-15 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0015_salesorder_salesorderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='vehicle_kilometers',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
