# Generated by Django 6.0.5 on 2026-06-15 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0016_alter_jobcard_vehicle_kilometers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobcard',
            options={'ordering': ['-job_card_date', '-vehicle_entry_time']},
        ),
    ]
