# Generated by Django 6.0.5 on 2026-06-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0017_alter_jobcard_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
