# Generated by Django 6.0.5 on 2026-06-29 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_advance_salary_month_transaction_incentive_incentivesetting'),
        ('jobcards', '0018_jobcard_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.employee'),
        ),
    ]
