# Generated by Django 6.0.5 on 2026-06-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0019_alter_jobcard_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
