# Generated by Django 6.0.5 on 2026-06-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0021_salesorder_share_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='base_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='gst_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
