# Generated by Django 6.0.5 on 2026-06-30 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0022_jobcard_base_amount_jobcard_gst_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcardpayment',
            name='base_collected',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='jobcardpayment',
            name='gst_collected',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
