# Generated by Django 6.0.5 on 2026-07-09 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_customerasset_vehicle_sub_type'),
        ('jobcards', '0023_jobcardpayment_gst_base_collected'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='customers.customer'),
        ),
    ]
