# Generated by Django 6.0.5 on 2026-07-22 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0024_jobcard_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='job_card_date',
            field=models.DateField(db_index=True),
        ),
    ]
