# Generated by Django 6.0.5 on 2026-06-11 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0009_alter_invoiceitem_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('product_name', 'product_unit', 'product_type', 'category', 'hsn_code')},
        ),
    ]
