# Generated by Django 6.0.5 on 2026-06-23 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0013_invoice_vendor_gst_number_invoice_vendor_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-invoice_date']},
        ),
    ]
