# Generated by Django 6.0.5 on 2026-06-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0014_alter_invoice_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='vendor_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
