# Generated by Django 6.0.5 on 2026-07-13 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estimation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone_number', models.CharField(max_length=10)),
                ('vehicle_name', models.CharField(max_length=255)),
                ('vehicle_type', models.CharField(choices=[('two_wheeler', 'Two Wheeler'), ('three_wheeler', 'Three Wheeler'), ('four_wheeler', 'Four Wheeler'), ('others', 'Others')], max_length=255)),
                ('vehicle_sub_type', models.CharField(choices=[('SUV', 'SUV'), ('CompactSUV', 'CompactSUV'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('others', 'Others')], max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EstimationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='estimation.estimation')),
            ],
        ),
    ]
