# Generated by Django 6.0.5 on 2026-07-20 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0002_estimation_share_token'),
        ('services', '0007_service_four_wheeler_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimationitem',
            name='selected_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.service'),
        ),
    ]
