# Generated by Django 6.0.5 on 2026-07-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0003_estimationitem_selected_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimation',
            name='vehicle_colour',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='estimation',
            name='vehicle_company',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='estimation',
            name='vehicle_model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
