# Generated by Django 6.0.5 on 2026-07-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0004_estimation_vehicle_colour_estimation_vehicle_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimation',
            name='vehicle_sub_type',
            field=models.CharField(choices=[('suv', 'SUV'), ('compact_suv', 'CompactSUV'), ('sedan', 'Sedan'), ('hatchback', 'Hatchback'), ('others', 'Others')], max_length=255),
        ),
    ]
