# Generated by Django 6.0.5 on 2026-05-23 16:35

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_add_role_to_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncentiveSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_threshold', models.IntegerField(default=10, help_text='Minimum job-card services completed in a month to earn incentive')),
                ('incentive_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fixed incentive amount paid when threshold is met', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Incentive Setting',
                'verbose_name_plural': 'Incentive Settings',
            },
        ),
        migrations.AddField(
            model_name='salaryadvance',
            name='salary_month',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salarytransaction',
            name='incentive',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='salarytransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='paid', max_length=20),
        ),
    ]
