# Generated by Django 6.0.5 on 2026-07-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_customer_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerasset',
            name='vehicle_sub_type',
            field=models.CharField(blank=True, choices=[('sedan', 'Sedan'), ('compact_suv', 'Compact SUV'), ('suv', 'SUV'), ('hatchback', 'Hatchback'), ('four_wheeler_others', '4-Wheeler Others')], default='', max_length=20),
        ),
    ]
